# Generated by Django 3.2.9 on 2022-01-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('motor_type', models.CharField(max_length=20)),
                ('power', models.CharField(max_length=20)),
                ('transmition', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Auto info',
                'verbose_name_plural': 'Auto info',
            },
        ),
    ]
