# Generated by Django 3.2.9 on 2022-01-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshare',
            name='image',
            field=models.ImageField(default=None, upload_to='home/static/images/cars'),
        ),
    ]
