# Generated by Django 3.2.9 on 2022-01-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_autoshare_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshare',
            name='image_link',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autoshare',
            name='image',
            field=models.ImageField(default=None, upload_to='cars/'),
        ),
    ]
